# setup-build-env.ps1 - weasel 构建环境一键准备（可重复执行，已就绪的步骤会自动跳过）
#
# 复现内容：
#   1. scoop 安装依赖: boost(含源码) / 7zip / xmake / pwsh
#   2. get-rime.ps1 -use dev 下载 librime 开发文件 (rime_*.h, rime.lib x86+x64, rime.dll, opencc 数据)
#   3. 用 scoop boost 自带源码 b2 编译 /MT 静态库到 <boost>\stage\lib (x64 + x86)
#      - scoop 的 boost 预编译库是 /MD 动态 CRT，与本项目 /MT 不匹配，必须自行编译
#   4. 生成 env.bat (BOOST_ROOT)
#   5. 生成 include/afxres.h stub（VS 未装 MFC 组件时的替代，见文件内注释）
#   6. 从 VS 复制 PerMonitorHighDPIAware.manifest 到仓库根
#
# 用法:
#   powershell/pwsh -ExecutionPolicy Bypass -File .\setup-build-env.ps1           # 仅准备环境
#   powershell/pwsh -ExecutionPolicy Bypass -File .\setup-build-env.ps1 -Build    # 准备后顺便 xmake 编译 x64+x86
#
# 依赖: scoop（本脚本会用它安装其余依赖）、Visual Studio 2022 含 ATL 组件（MFC 可选）
param(
  [switch]$Build
)
$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
if (-not $repo) { $repo = Split-Path -Parent $MyInvocation.MyCommand.Path }

function Step($msg) { Write-Host "`n=== $msg ===" -ForegroundColor Cyan }

# --------------------------------------------------------------------------
Step "0/6 检查 scoop 及依赖包 (boost 7zip xmake pwsh)"
if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
  throw "scoop not found; install scoop first: https://scoop.sh"
}
foreach ($app in @('boost', '7zip', 'xmake', 'pwsh')) {
  $installed = [bool](scoop prefix $app 2>$null)
  if ($installed) {
    Write-Host "  [ok] $app"
  } else {
    Write-Host "  [install] $app (via scoop) ..."
    scoop install $app
    if ($LASTEXITCODE -ne 0) { throw "scoop install $app failed" }
  }
}

# --------------------------------------------------------------------------
Step "1/6 定位 boost"
$boostRoot = (scoop prefix boost 2>$null)
if ($boostRoot) { $boostRoot = $boostRoot.Trim() }
if (-not $boostRoot -or -not (Test-Path (Join-Path $boostRoot 'boost\version.hpp'))) {
  throw "boost (scoop) not found; expected ~\scoop\apps\boost\current"
}
Write-Host "  BOOST_ROOT = $boostRoot"

# --------------------------------------------------------------------------
Step "2/6 生成 env.bat"
Set-Content -Path (Join-Path $repo 'env.bat') -Encoding ASCII -Value @(
  'rem Generated by setup-build-env.ps1: boost built from scoop package into stage\lib'
  "set BOOST_ROOT=$boostRoot"
)
Write-Host "  env.bat written"

# --------------------------------------------------------------------------
Step "3/6 生成 include/afxres.h stub (仅在 VS 未安装 MFC 组件时需要)"
$afxres = Join-Path $repo 'include\afxres.h'
if (Test-Path $afxres) {
  Write-Host "  [skip] already exists"
} else {
  Set-Content -Path $afxres -Encoding ASCII -Value @(
    '// Minimal stand-in for the MFC afxres.h, which is only pulled in by the'
    '// AppStudio TEXTINCLUDE 2 boilerplate in the .rc files. The resources here'
    '// use nothing from MFC itself; the standard Win32 resource definitions from'
    '// the Windows SDK are all that is needed.'
    '#ifndef _AFXRES_H'
    '#define _AFXRES_H'
    '#include "winres.h"'
    '#endif'
  )
  Write-Host "  [created] include/afxres.h"
}

# --------------------------------------------------------------------------
Step "4/6 复制 PerMonitorHighDPIAware.manifest 到仓库根"
$manifest = Join-Path $repo 'PerMonitorHighDPIAware.manifest'
if (Test-Path $manifest) {
  Write-Host "  [skip] already exists"
} else {
  $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
  if (-not (Test-Path $vswhere)) { throw "vswhere not found; is Visual Studio installed?" }
  $vsDir = (& $vswhere -latest -products * -property installationPath).Trim()
  $candidates = @(
    Get-Item "$vsDir\VC\Tools\MSVC\*\include\Manifest\PerMonitorHighDPIAware.manifest" -ErrorAction SilentlyContinue
    Get-Item "$vsDir\VC\Tools\MSVC\*\atlmfc\include\Manifest\PerMonitorHighDPIAware.manifest" -ErrorAction SilentlyContinue
  )
  if (-not $candidates) {
    $candidates = Get-ChildItem $vsDir -Recurse -Filter 'PerMonitorHighDPIAware.manifest' -ErrorAction SilentlyContinue | Select-Object -First 1
  }
  if (-not $candidates) { throw "PerMonitorHighDPIAware.manifest not found under $vsDir" }
  Copy-Item $candidates[0].FullName $manifest
  Write-Host "  [copied] $($candidates[0].FullName)"
}

# --------------------------------------------------------------------------
Step "5/6 获取 librime 开发文件 (get-rime.ps1 -use dev)"
$needRime = -not (
  (Test-Path (Join-Path $repo 'include\rime_api.h')) -and
  (Test-Path (Join-Path $repo 'lib64\rime.lib')) -and
  (Test-Path (Join-Path $repo 'lib\rime.lib')) -and
  (Test-Path (Join-Path $repo 'output\rime.dll')) -and
  (Test-Path (Join-Path $repo 'output\Win32\rime.dll')))
if ($needRime) {
  # get-rime.ps1 依赖 PowerShell 7 语法，必须用 pwsh 运行
  Push-Location $repo
  try {
    pwsh -NoProfile -ExecutionPolicy Bypass -File .\get-rime.ps1 -use dev
    if ($LASTEXITCODE -ne 0) { throw "get-rime.ps1 failed" }
  } finally { Pop-Location }
} else {
  Write-Host "  [skip] rime files already present"
}

# --------------------------------------------------------------------------
Step "6/6 编译 boost /MT 静态库到 stage\lib (x64 + x86)"
$threadLib = Get-ChildItem (Join-Path $boostRoot 'stage\lib') -Filter 'libboost_thread-*mt-s-x64-*.lib' -ErrorAction SilentlyContinue
if ($threadLib) {
  Write-Host "  [skip] $($threadLib.Name) already present"
} else {
  $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
  $vsDir = (& $vswhere -latest -products * -property installationPath).Trim()
  $vcvars = Join-Path $vsDir 'VC\Auxiliary\Build\vcvars64.bat'
  if (-not (Test-Path $vcvars)) { throw "vcvars64.bat not found under $vsDir" }
  # 与 build.bat :build_boost 的参数保持一致，仅保留 link=static runtime-link=static variant=release
  $cmd = @"
@echo off
call "$vcvars" || exit /b 1
cd /d "$boostRoot"
if not exist b2.exe call bootstrap.bat || exit /b 1
b2 -j%NUMBER_OF_PROCESSORS% --with-filesystem --with-json --with-locale --with-regex --with-serialization --with-system --with-thread define=BOOST_USE_WINAPI_VERSION=0x0603 toolset=msvc link=static runtime-link=static threading=multi variant=release architecture=x86 address-model=64 stage || exit /b 1
b2 -j%NUMBER_OF_PROCESSORS% --with-filesystem --with-json --with-locale --with-regex --with-serialization --with-system --with-thread define=BOOST_USE_WINAPI_VERSION=0x0603 toolset=msvc link=static runtime-link=static threading=multi variant=release architecture=x86 address-model=32 stage || exit /b 1
"@
  $tmpCmd = Join-Path $env:TEMP 'weasel-boost-stage.cmd'
  Set-Content -Path $tmpCmd -Encoding ASCII -Value $cmd
  Write-Host "  building boost static libs (takes a few minutes) ..."
  cmd /c $tmpCmd
  $ok = ($LASTEXITCODE -eq 0)
  Remove-Item $tmpCmd -ErrorAction SilentlyContinue
  if (-not $ok) { throw "boost stage build failed" }
  $count = (Get-ChildItem (Join-Path $boostRoot 'stage\lib') -Filter '*.lib').Count
  Write-Host "  [done] stage\lib contains $count static libs"
}

# --------------------------------------------------------------------------
if ($Build) {
  Step "构建 weasel (x64 + x86, 无需 Developer Command Prompt)"
  Push-Location $repo
  try {
    xmake f -a x64 -m release -y
    if ($LASTEXITCODE -ne 0) { throw "xmake config x64 failed" }
    xmake -y
    if ($LASTEXITCODE -ne 0) { throw "xmake build x64 failed" }
    xmake f -a x86 -m release -y
    if ($LASTEXITCODE -ne 0) { throw "xmake config x86 failed" }
    xmake -y
    if ($LASTEXITCODE -ne 0) { throw "xmake build x86 failed" }
  } finally { Pop-Location }
}

Write-Host "`n=== 环境就绪 ===" -ForegroundColor Green
Write-Host '  编译(任意 shell):  xmake f -a x64 -m release -y ; xmake        (x86 同理换 -a x86)'
Write-Host '  传统方式:          在 Developer Command Prompt 中运行 xbuild.bat'
Write-Host '  注意: scoop 升级 boost 后 stage\lib 会被清空，重跑本脚本即可重新编译'
